#!/usr/bin/env python3
"""Build the weekly training discussion body from summary.json."""
import json
from datetime import datetime, timezone


def main():
    with open("/tmp/summary.json") as f:
        s = json.load(f)

    status = "✅ ALL GATES PASSED" if s["ci_gates_passed"] else "❌ GATES FAILED"
    sev = s["findings_by_severity"]

    top_suggestions = s.get("top_suggestions", [])
    if top_suggestions:
        suggestions_lines = []
        for x in top_suggestions:
            prio = x.get("priority", "?").upper()
            area = x.get("area", "?")
            sug = x.get("suggestion", "?")
            suggestions_lines.append(f"- [{prio}] **{area}**: {sug}")
        suggestions = "\n".join(suggestions_lines)
    else:
        suggestions = "_None_"

    body = f"""## Weekly Training Report — {datetime.now(timezone.utc).strftime('%Y-%m-%d')}

### {status}

| Metric | Value |
|--------|-------|
| Contracts scanned | {s['contracts_scanned']} |
| Contests | {s['contests']} |
| Total imports | {s['total_imports']} |
| Dep resolution | {s['dep_resolution_pct']}% (npm {s['npm_resolution_pct']}% · rel {s['rel_resolution_pct']}%) |
| Total findings | {s['total_findings']} |
| Critical | {sev.get('critical', 0)} |
| High | {sev.get('high', 0)} |
| Medium | {sev.get('medium', 0)} |
| Low | {sev.get('low', 0)} |
| Informational | {sev.get('informational', 0)} |
| Privacy violations | {s['privacy_violations']} |
| Avg scan time | {s['avg_scan_time_s']}s |
| Total time | {s['total_time_s']}s |
| Regression drifts | {s['regression_drifts']} |
| Improvement suggestions | {s['improvement_suggestions']} |

### Top Improvement Suggestions
{suggestions}

---
*Auto-generated by VeilPiercer Training Pipeline · `train_pipeline.py --full`*
"""

    with open("/tmp/discussion_body.md", "w") as f:
        f.write(body)

    # Signal success to GitHub Actions
    print("body_built=true")


if __name__ == "__main__":
    main()
